# SET THE PATH AT WHICH THE POSTPROCESSED DATA WILL BE STORED
pickles_path = ''

################ ONLY NEEDED IF PROCESSING RAW DATA #####################
# SET THE PATH AT WHICH RAW RADIOSONDE DATA IS STORED 
rs_path = ''
# SET THE PATH AT WHICH RAW CALIPSO DATA IS STORED
c_path = ''